use_frameworks!

target 'YYCategory_Example' do
  pod 'YYCategory', :path => '../'

  target 'YYCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
